---
title: "Discussion"
author: "Chris Adlam"
date: "2/11/2020"
output:
 pdf_document: default
 word_document: default
 html_document: default
bibliography: bibliography3.bib
csl: ecology-and-society.csl
---

# Discussion

This study found that management options that mitigate the risk of high-severity fires by reducing canopy cover and continuity were also favorable to enhanced biodiversity outcomes for birds, plants, and lichens. Diversity for all three taxa was as high or higher in multiple burns and thin+burn plots than in either the high severity burns or the dense, long-unburnt or low-severity burn stands because the intermediate conditions provided habitat for both early and late seral species. Low-severity burns were not linked to a detectable change in species composition compared with long-unburnt stands. These stands had similar to lower diversity in birds, plants, lichens and insects compared with high-severity burn patches. Management that aims to mitigate the risk of high-severity fire by reducing canopy cover to 30-60% can also meet biodiversity objectives by accommodating both early and late seral associated species.

This finding is encouraging given the focus on increasing the pace and scale of forest restoration across the West [@charnleyAllLandsApproaches2016; @hessburgRestoringFireproneInland2015; @northUsingFireIncrease2012]. Recent policy priorities have emphasized the expansion of forest restoration, while collaborative landscape restoration partnerships such as the WKRP have been building grassroots momentum and multi-stakeholder consensus for such projects [@harlingWesternKlamathRestoration2014; @lakeIntegrationTraditionalWestern2018]. In addition to the goal of reducing the risk of high-severity fires, such treatments aim to address the threat to biodiversity from fire suppression, which has reduced successional diversity and areas of open forest. These were once much more widespread due to historically frequent, low-severity fires, particularly in areas with a high level of ignitions from Native Americans [@metlenRegionalLocalControls2018; @taylorSocioecologicalTransitionsTrigger2016; @crawfordLateHoloceneFire2015; @lakeHistoricalCulturalFires2013]. Restoring a more open forest structure is expected to increase diversity in understory plants [@waymanInitialResponseMixedconifer2007; @websterLongtermVegetationResponses2010] and birds [@gainesShortTermEffectsThinning2010; @gainesShortTermResponseLand2007; @kaliesStandStructureBreeding2013; @alexanderUsingRegionalBird2017]. Many studies have documented an increase in diversity at intermediate disturbance and canopy levels [@richterSpeciesDiversityFire2019], although it is unclear whether this tends to benefit early-seral or late-seral associated species. @stevensForestDisturbanceAccelerates2015 found that intermediate disturbance levels favored the coexistence of species with a northern (temperate) and southern (xeric) biogeographical affinities, while only the latter persisted after high severity burns. In contrast, some researchers have noted the benefits of high-severity fire for many species and suggested that forest restoration could damage habitat used by late-seral associates while creating conditions that are unsuitable for species associated with post-fire early-seral habitats [@odionExaminingHistoricalCurrent2014; @odionAlternativeCommunityStates2010]. This study demonstrates that actively or passively restored stands are more diverse precisely because they accommodate both species associated with denser forests, and those associated with high-severity patches.

Despite a trend of increasing fire size, fire frequency remains significantly below historic levels across much of the landscape in the Klamath Mountains [@fryInfluenceHumansClimate2006; @taylorFireHistoryLandscape1998; @steelFireFrequencyseverityRelationship2015; @millerTrendsCausesSeverity2012]. In other ecoregions with predominantly low- to moderate-severity fires, fire suppression has caused increases in canopy cover. Mixed conifer forests of the Sierra Nevada historically had a canopy cover of 17-50% [@stephensHistoricalCurrentLandscapescale2015; @saffordNaturalRangeVariation2017]. While precise estimates of historical canopy cover are lacking for the Klamath Mountains, it is clear that open forests and other vegetation types dependent on frequent fires have been lost across the region due to fire suppression, leading to a more homogenous, denser forest [@taylorSpatialPatternsControls2003a; @odionAlternativeCommunityStates2010; @skinnerKlamathMountainsBioregion2006; @skinnerChangeSpatialCharacteristics1995].

In this study, stands where fire had been excluded had the lowest plant species richness and the smallest pool of species for both birds and plants. Only select groups of species appear to prefer these conditions, including shade-tolerant plants and bark-gleaning and canopy-dwelling bird species. Fire-sensitive species, including all lichens and a small number of plants (eg. *Goodyera oblongifolia*) were also associated with these stands and absent from high-severity burns (lichens began to recolonize as early as 16 years after a high-severity burn). Meanwhile, the latter were home to a variety of shade-intolerant grasses, shrubs and forbs, and open area, shrub-nesting and cavity-nesting bird species that were found rarely, if ever, in unburnt stands. Several taxa of insect pollinators and herbivores were also strongly associated with high-severity burns. Arthropods are an important part of the diet of many bird species, and their increase after fires may favor insectivorous birds [@seavySongbirdResponseWildfire2014]. Early-seral habitats created by fire are recognized for their importance to many taxa, including rare species [@swansonBiologicalAssociatesEarlyseral2014]. Most plant and many bird species found in mature stands persisted in high-severity burn patches, a finding consistent with other studies in the region [@donatoVegetationResponseShort2009]. While the species of denser, fire-suppressed stands and those of post-fire early seral habitats are largely segregated in today's forested landscape, this pattern may not be representative of historical conditions in which finer-scale heterogeneity was prevalent [@taylorSpatialPatternsControls2003a; @hanberryOpenForestEcosystems2020; @skinnerKlamathMountainsBioregion2006]. However, few studies have clarified whether reductions in canopy cover following lower severity burns, multiple burns or thin+burn treatments can allow for these two groups of species to coexist within stands. 

However, the sharp distinction between the species communities of denser forests and high-severity patches was not significantly altered by the occurrence of low-severity fire. While it might have been expected that surface fires would play a restorative role in fire-suppressed stands (leading to an increase in shade-intolerant species for example), the small magnitude of the reduction in canopy cover after a single low-severity burn was insufficient to achieve this result. Other studies in mixed conifer forest have suggested that a considerable reduction in canopy cover (to 30-50%) is necessary before understory richness can be expected to increase [@abellaEffectsTreeCutting2015], with similar canopy cover levels suggested to maximize bird diversity [@whiteConservationAvianDiversity2013]. Douglas-firs (and white firs at higher elevations) are unlikely to be thinned by surface fires, particularly once they have reached 30cm dbh [@beckerCanLowseverityFire2016; @collinsImpactsFireExclusion2011; @knappLongtermOverstoryUnderstory2013]. Trees that have established since the criminalization of Indigenous burning (mid-1800s) and later the establishment of the policy of fire-suppression (around 1910) have reached this fire-resistant size in the productive forests of the Klamath Mountains. Further research is needed to evaluate the potential for multiple low-severity fires to reduce the density of these post-fire suppression trees. Low-severity fires prior to fire suppression were likely sufficient to maintain forest openings and early seral vegetation [@skinnerChangeSpatialCharacteristics1995], but in today's fire suppressed stands, a greater level of tree mortality will likely be needed to restore a more open, patchy forest structure critical to the maintenance of biodiversity. Since low-severity fires are not significantly changing forest structure and species composition, management options that restore a lower canopy cover need to be considered.

The multiple burns and thin+burn stands in this study had a canopy cover of 30-75% (mean = 48%, sd = 15%), and were associated with the highest levels of species richness for birds and plants. Lichen species richness was also similar to that of the low-severity and unburnt stands. I also found that canopy cover was negatively associated with bird and plant species richness within these habitats. Canopy cover is recognized as a key driver of species diversity [@stephensCoarseWoodyDebris2007; @stevensFireSeverityChanging2019], and my findings echo the suggestion by Abella and Springer that a reduction in canopy cover to 30-50% is needed to achieve significant increases in species diversity [@abellaEffectsTreeCutting2015]. When management results in this level of canopy cover, species typically restricted to high-severity burns and those that occur in denser mature forests can coexist in a single stand. 

Managing wildfires to achieve resource objectives is a strategy that is recommended for its outcomes for bird diversity [@stephensFireSeverityAffects2015; @fontaineBirdCommunitiesFollowing2009], plant diversity [@laughlinReferenceConditionsWildfire2004], and ecosystem resilience [@barrosWildfiresManagedRestoration2018; @boisrameVegetationChange40years2017; @nesmithComparisonEffectsPrescribed2011; @estesFactorsInfluencingFire2017]. While there has been a focus on the capacity of high-severity reburns to perpetuate "non-forest" vegetation conditions [@odionAlternativeCommunityStates2010; @tepleyVulnerabilityForestLoss2017; @thompsonFactorsAssociatedCrown2010], multiple low- to moderate-severity burns can also increase fine-scale heterogeneity by creating multi-layered, patchy stands with canopy cover levels intermediate between unburnt (and low-severity) stands and high-severity burns. By creating gaps in the canopy (particularly that of resprouting hardwoods), short interval reburns favor the coexistence of species associated with mature forests and early seral species (particularly annual and disturbance-associated species and species with a long-lasting seed bank) [@donatoVegetationResponseShort2009]. My results similarly suggest that such areas represent biodiversity hotspots on the landscape because the structure of these stands accommodates both fire-sensitive species (e.g. shade-tolerant plants, canopy-dwelling birds and lichens) and fire-dependent species (eg. shade-intolerant herbaceous plants and shrub-nesting birds). 

Thinned and burnt stands achieved the same result, particularly when there had been a significant reduction in canopy cover. As was the case for the multiple burns, I focused my sampling on stands with a canopy cover of 30-70%. This represents a important reduction in canopy cover and may not represent standard underburn operations, which may make little impact on stand structure and thus biodiversity [@seavyMeasuringEcologicalEffects2006]. But this study joins others in highlighting the ecological benefits of higher severity burns, or at least treatments that include patches of high-severity [@fuleEffectsIntensePrescribed2004; @stephensEffectsForestFuelReduction2012]. Just like low-severity burns in this study, treatments that maintain a high canopy cover are unlikely to stimulate a response of understory diversity. Despite the potential benefits of treating stands to reverse the effects of fire exclusion, such treatments remain very scarce in the study region. This led to some sacrifices in sampling rigor (eg. sites were more spatially clustered), and as a result caution is needed in interpreting some of the results (eg. lower beta diversity in the thin+burn stands). More importantly, while the results are encouraging, the realtively small footprint of active forest restoration brings into question the ability for agencies and landscape collaboratives to deploy such treatments on the scale that is needed. Only 20% of the area in need of restoration annually is receiving treatment, and this will need to be re-treated every 15-30 years [@northUsingFireIncrease2012]. Much more widespread restoration efforts will be needed, for example through collaborative approaches such as the WKRP. Wildland fire use should also be embraced to expand the scale of restoration, when weather and fuels conditions are appropriate, and consistent with the preservation of cultural and biological resources [@northUsingFireIncrease2012]. In the meantime, unplanned ignitions -including small to moderately sized high-severity burn patches- can help maintain biodiversity by providing early successional habitat in the fire suppressed forests of the Klamath Mountains and across the West [@huttoMoreEcologicallyInformed2016].

This study had other weaknesses aside from the difficulty in finding acceptable actively restored stands. The number of samples and variation associated with complex topographic and environmental factors did not allow for an in-depth analysis of the role of time-since-fire, which may have masked the response of some species [@smuckerChangesBirdAbundance2005]. Scale-related challenges are common in ecological research, and this study was no exception, taking into account only stand-level variables but leaving out potentially important landscape patterns [@bettsThresholdsForestBird2010]. Lastly, it would be useful to more thoroughly investigate the full range of outcomes from multiple burns and thin+burn treatments, including quantifying their spatial extent. This study joins others in showing that positive biodiversity outcomes are possible under some conditions, but to what extent these are realized remains to be determined. Despite these caveats, this study has clear and important management implications.

## Management implications

Fire suppressed stands have similar or lower plant and bird diversity (alpha, beta, gamma diversity) than high-severity burn burns, and a single low-severity burn does not appear to change this pattern. While high-severity burns are important for biodiversity when compared with unburnt/low-severity stands, species that are associated with both of these habitats also favor multiple burns and thinned and burnt stands. As a result, such stands are more diverse than either high-severity burns or unburnt/low-severity burn stands. This suggests that both active (thin+burn) and passive (wildland fire use) management can achieve biodiversity conservation goals while also achieving fuels reduction and forest and community resilience objectives. 

Fuels reduction treatments can be conducted in a way that benefits biodiversity [@dodsonDryConiferousForest2010; @dodsonUnderstoryVegetationResponse2008; @waymanInitialResponseMixedconifer2007; @stevensForestDisturbanceAccelerates2015]. However, canopy cover and small to medium tree density must be significantly reduced to achieve such benefits [@abellaEffectsTreeCutting2015; @kaliesStandStructureBreeding2013], mechanical treatments should be followed by prescribed burning [@stevensForestDisturbanceAccelerates2015; @kaneUnderstoryVegetationResponse2010; @waymanInitialResponseMixedconifer2007], and repeated treatments are necessary [@goodwin15yearPosttreatmentResponse2018]. This and other studies have found that such treatments are compatible with the conservation of many late seral and fire-sensitive species, including lichens [@millerAlteredFireRegimes2018]. Multiple burns can achieve similar results, suggesting that wildland fire use should be increased to promote diverse forests at a larger scale than possible through active restoration treatments [@northUsingFireIncrease2012]. In the absence of passive or active restoration, mosaics of different fire severities, including high-severity patches, are important to the maintenance of biodiversity in the fire suppressed forests of the Klamath Mountains. 

Despite the benefits of forest thinning for biodiversity and risk reduction, managers face regulatory requirements to maintain closed canopy stands for the protection of listed late seral species, such as the Northern Spotted Owl/California Spotted Owl (*Strix occidentalis*). These policies can drive land managers towards a focus on late seral habitats, sometimes conflicting with the management of culturally important species [@longRestoringCaliforniaBlack2015], and with multi-species conservation approaches [@whiteConservationAvianDiversity2013]. However, with proper spatial prioritization and thoughtful deliberation, reducing canopy cover to the level of the managed stands in this study may be compatible with Spotted Owl conservation [@leeAssessingRisksSpotted2005; @winfordEffectsFuelTreatments2015]. In addiition, many late seral associates in forests with mixed severity fire regimes benefit from the complex intermixing of different seral stages [@hagarWildlifeSpeciesAssociated2007]. Landscape-level planning that promotes a diversity of habitats rather than seeking to implement narrow prescriptions across large areas is most likely to achieve multi-species conservation goals, while conserving threatened late seral species [@whiteConservationAvianDiversity2013].

Forest collaboratives often try to maximize additional objectives besides biodiversity conservation and fuels reduction. In the case of the WKRP, management for Indigenous cultural uses is an important priority. It is unclear whether the patterns in species richness and composition found in this study match the value of each habitat for the purposes of Indigenous cultural practitioners. Species of cultural importance were found in all habitats (table 2), but they may be of insufficient quality or quantity, or too difficult to access depending on the structure of the habitat. For example, the growth in recent high-severity burn patches is often too dense for elders to access cultural plants, whether they are present or not. Meanwhile, basketry plants growing in exposed conditions do not develop in a way that is optimal for the use of weavers [@marks-blockEffectsUnderstoryFire2019; @hummelUsingForestKnowledge2015]. While this study found that biodiversity is maximized in stands with intermediate canopy cover, further research is needed to determine whether such stands also present high cultural value from the perspective of Karuk cultural practitioners. Alternative ignition patterns, pre- and post-treatment interventions, and adaptive management based on traditional ecological knowledge will likely be needed for optimal management of cultural species beyond their conservation value.

# Acknowledgements
I would like to extend my deepest gratitude to the Karuk Tribe and tribal members and fire practitioners including Frank Lake, Bill Tripp, Renée Stauffer, and members of the Karuk Research Approval Board for their guidance. I am also grateful to the staff of the USDA Forest Service Six Rivers and Klamath National Forests for their support, and to my academic mentors at UC Davis, including Beth Rose Middleton, Hugh Safford, and Dan Potter. Several brave interns helped me gather the data and process insect specimens: Jacob Wilson, Diana Cuevas, Shaden Cortez, Vincent Ho, and Sierra Schluep. Funding was provided by the Henry A. Jastro Research Fellowship, California Lichen Society, Northern California Botanists, and California Native Plant Society.

# References
```{r}
#Run this to clean up duplicate or removed citations
#tidy_bib_file(
# rmd_file = "report.Rmd"
# , messy_bibliography = "references.bib"
# , file = "tidy_references.bib"
#)

```

