---
title: "GJAM"
author: "Chris Adlam"
date: "3/7/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if(!require('pacman'))install.packages('pacman')
pacman::p_load(gjam)
```


```{r}

f   <- gjamSimData(n = 500, S = 10, typeNames = 'CA')
ml1  <- list(ng = 1000, burnin = 200, typeNames = f$typeNames)
out1 <- gjam(f$formula, f$xdata, f$ydata, modelList = ml1)
pl  <- list(trueValues = f$trueValues, GRIDPLOTS = T)
gjamPlot(output = out1, plotPars = pl)

par(bty = 'n', mfrow = c(1,3), family='')
plot(f$trueValues$beta, out$parameters$betaMu, cex = .2)
plot(f$trueValues$corSpec, out$parameters$corMu, cex = .2)
plot(f$y,out$prediction$ypredMu, cex = .2)



site_data <- site_data[order(site_data["site_id"]),] %>% 
  mutate(cov_cat = ifelse(tree_cov > 65, 3, ifelse(tree_cov > 35, 2, 1)))
xdata1 <- site_data[,c(1,3,6,7,8,34)] 
ydata1 <- plant_mat_pa_w[,-1]# %>% 
#  mutate("DUMB" = 1)  # adding dummy species (eg. Webster 2010) 

ydata1[111,] <- colSums(ydata1, na.rm = TRUE)
ydata1 <- ydata1[, (ydata1[111, ]) > 10]
ydata1 <- ydata1[-111, ] %>%
  mutate_if(is.character, as.numeric)
#xdata1 <- xdata1 %>% 
#  mutate_if(is.character, as.numeric)

xdata1$tsf_cat <- as.numeric(xdata1$tsf_cat)
library(reshape)
md <- melt(xdata1, id = c("site_id", "tsf_cat", "tree_cov", "shrub_cov", "cov_cat"))

xdata2 <- cast(md, site_id + tsf_cat + tree_cov + shrub_cov + cov_cat~value)

xdata2 <- as.data.frame(xdata2) %>%
  mutate_if(is.factor, as.character)

xdata3 <- xdata2 %>%
  mutate_at(vars(h, l, u , multiple, Rx), funs(replace(., !is.na(.), 1))) %>%
  mutate_at(vars(h, l, u , multiple, Rx), funs(replace(., is.na(.), 0))) %>%
  mutate_if(is.character, as.numeric) %>% 
  mutate(ul = u + l)  %>% 
  mutate(manag = multiple + Rx) %>% 
  mutate(type = ifelse(h == 1, 1, ifelse(manag == 1, 2, 3)))

formula <- as.formula( ~ tree_cov + shrub_cov + cov_cat + type)

ml  <- list(ng = 1000, burnin = 200, typeNames = "PA")
out1 <- gjam(formula, xdata3, ydata1, modelList = ml)

pl  <- list(GRIDPLOTS=T, SAVEPLOTS = T)
gjamPlot(output = out1, plotPars = pl)

#fit$clusterOrder
#fit$clusterIndex







install.packages("repmis")
library(repmis)
d <- "https://github.com/jimclarkatduke/gjam/blob/master/forestTraits.RData?raw=True"
source_data(d)
xdata <- forestTraits$xdata[,c(1,2,8)]

xdata[1:5,]
formula <- as.formula( ~ temp + deficit + soil )


y  <- gjamReZero(forestTraits$treesDeZero)  # extract y
treeYdata  <- gjamTrimY(y,10)$y             # at least 10 plots
dim(treeYdata)
treeYdata[1:5,1:6]

rl   <- list(r = 8, N = 20)
ml   <- list(ng = 2500, burnin = 500, typeNames = 'DA', reductList = rl)
form <- as.formula( ~ temp*deficit + I(temp^2) + I(deficit^2) )
out  <- gjam(form, xdata = xdata, ydata = treeYdata, modelList = ml)
specNames <- colnames(treeYdata)
specColor <- rep('black',ncol(treeYdata))
specColor[ c(grep('quer',specNames),grep('cary',specNames)) ] <- 'brown'
specColor[ c(grep('acer',specNames),grep('frax',specNames)) ] <- 'darkgreen'
specColor[ c(grep('abie',specNames),grep('pice',specNames)) ] <- 'blue'


pl   <- list(SMALLPLOTS = F, GRIDPLOTS=T, specColor = specColor)
gjamPlot(output = out, plotPars = pl)

?gjamPlot
```

