---
title: "GLM"
author: "Chris Adlam"
date: "9/18/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data
```{r}
library (plyr)
library (dplyr)
library (reshape2)
library(tidyr)

plant_dat <- read.csv("data/plant_data_natives.csv", header=TRUE)

site_data <- read.csv("data/site_data.csv")


#install.packages("fuzzySim") doesnt work, so here's the function; serves to convert from presence only to presence-absence

splist2presabs <- function(data, sites.col, sp.col, keep.n = FALSE) {
  # version 1.1 (7 May 2013)
  # data: a matrix or data frame with your localities and species (each in a different column)
  # sites.col: the name or index number of the column containing the localities
  # sp.col: the name or index number of the column containing the species names or codes
  # keep.n: logical, whether to get in the resulting table the number of times each species appears in each locality; if false (the default), only the presence (1) or absence (0) are recorded

  stopifnot(
    length(sites.col) == 1,
    length(sp.col) == 1,
    sites.col != sp.col,
    sites.col %in% 1 : ncol(data) | sites.col %in% names(data),
    sp.col %in% 1 : ncol(data) | sp.col %in% names(data),
    is.logical(keep.n)
  )

  presabs <- table(data[ , c(sites.col, sp.col)])
  presabs <- as.data.frame(unclass(presabs))
  if (!keep.n)  presabs[presabs > 1] <- 1
  presabs <- data.frame(row.names(presabs), presabs)
  names(presabs)[1] <- names(subset(data, select = sites.col))
  rownames(presabs) <- NULL
  return(presabs)
}  # end splist2presabs function

# executing function and going from wide to long:
plant_dat_pa <- splist2presabs(plant_dat, sites.col = 2, sp.col = 3) %>% 
  gather(key = species, value = pa, ABCO:WOFI)
head(plant_dat_pa)

# Adding in the sev and tsf data
head(site_data)

#merge(plant_dat_pa, site_data[, c('sev', 'tsf')], by= 'site_id')
plant_glm <- merge(plant_dat_pa, site_data, by= 'site_id') %>% 
  mutate(tsf_cat = as.factor(as.character(tsf_cat))) # if tsf_cat is numeric, model output is gibberish; must change to factor

# Now the GLM
#bin.glm1 = glm(pa~sev+tsf_cat,data=plant_glm,family=binomial)

#summary(bin.glm1)
#step(bin.glm1) 

#likelihood ratio test
#results.reduced =glm(data=plant_glm, pa ~ 1, family=binomial)
#anova(results.reduced,bin.glm1, test="Chisq")


```

# GLM and LRT for selected species (more than 10 detections?)
```{r}
# now just for Madia
Madia_glm <- plant_dat_pa_l %>% 
  merge(., site_data, by= 'site_id') %>% 
  filter(species == "Madia")

# Now the GLM
bin.glm1 <- glm(pa~sev+tsf_cat, data=Madia_glm, family=binomial)

summary(bin.glm1)
#step(bin.glm1) 

#likelihood ratio test
results.reduced <- glm(data=Madia_glm, pa ~ 1, family=binomial)
anova(results.reduced,bin.glm1, test="Chisq")



install.packages("multcompView")
library(multcompView)
library(mvabund)



# now just for ANMAD
ANMAD_glm <- plant_dat_pa_l %>% 
  merge(., site_data, by= 'site_id') %>% 
  filter((tsf < 25 & tsf >= 4) | sev == "u") %>% 
  mutate(sev2 = ifelse(sev == 'h' , "1", ifelse(sev == 'l' , "2", ifelse(sev == 'u', "2", ifelse(sev == 'multiple', "3", "4"))))) %>% 
  mutate(tsf2 = ifelse(fire == "unburnt", "5",ifelse(tsf < 9 , "1", ifelse(tsf < 15 & tsf > 8 , "2", ifelse(tsf > 13, "3", "6"))))) %>% 
  filter(species == "ELGL") %>% 
  mutate(sev2 = as.factor(sev2))



mod <- ANMAD_glm %>%
  mutate(sev2 = as.factor(sev2)) %>% 
#  mutate(num_sites = dplyr::count(site_id)) %>% 
  group_by(sev2) %>% 
  mutate(num_occ = sum(pa)) %>% 
  add_tally() %>% 
  mutate(freq = num_occ/n) %>% 
  dplyr::select(sev2, freq)

mod<-unique(mod)

ggplot(mod, aes(x=sev2, y=freq)) +
  geom_point()

#relevel(warpbreaks$tension, ref = "M")

site_data %>% 
  dplyr::count(sev)
  
    group_by(sev) %>% 
    tally()

mtcars %>% dplyr::count(cyl)

# GLM using manyglm
bin.glm2 <- manyglm(pa ~ sev2, family="binomial", data=ANMAD_glm)

anova(bin.glm2, nBoot=199, test="wald")
summary(bin.glm2, resamp="montecarlo")
step(bin.glm2) 

abund <- mvabund(ANMAD_glm$pa)
treatment <- as.character(ANMAD_glm$sev2)
## pairwise comparison 
msolglm <- manyglm(abund ~ treatment)
anova(msolglm, pairwise.comp = treatment, nBoot = 199)




# trying glmer
library(lme4)

fit.bin <- glmer(pa ~ sev2 + (1|site_id), family=binomial, data=ANMAD_glm)

par(mfrow=c(1,2))
plot(residuals(fit.bin)~fitted(fit.bin),main="residuals v.s. Fitted")
qqnorm(residuals(fit.bin))

nBoot <- 1000
lrStat <- rep(NA,nBoot)
ft.null <- glmer(pa ~ 1 + (1|site_id) ,family=binomial, data=ANMAD_glm) #null model
ft.alt <- glmer(pa ~ sev2 + (1|site_id) ,family=binomial, data=ANMAD_glm) #alternate model

lrObs <- 2*logLik(ft.alt) - 2*logLik(ft.null) #observed test stat

 for(iBoot in 1:nBoot)
{
  ANMAD_glm$paSim <- unlist(simulate(ft.null)) #resampled data
  tryCatch({#sometimes the glmer code doesn't converge
    
    bNull <- glmer(paSim ~ 1 + (1|site_id) ,family=binomial, data=ANMAD_glm)#null model
    bAlt <- glmer(paSim ~ sev2 + (1|site_id) ,family=binomial, data=ANMAD_glm)#alternate model
    lrStat[iBoot] <- 2*logLik(bAlt) - 2*logLik(bNull) #resampled test stat
    },warning=function(war) {lrStat[iBoot]=NA},error=function(err){lrStat[iBoot]=NA}) #if code doesn't converge skip sim
}
mean(lrStat>lrObs,na.rm=T) #P-value for test of Estuary effect

# Are these two models significantly different from one another? Look for a p < .05
# (Likelihood ratio test)
anova(ft.alt, ft.null)

# What's the model ANOVA table
anova(ft.alt)

# capture.output(anova(mod_add),file="alpha_rich_anova")

# Estimated means between groups within each year
means = emmeans(ft.alt, specs = "sev2", adjust = "tukey") # modified

# All pairwise comparisons
paircomp = pairs(means)

# Assigning labels to each groups
cld(means)





mod <- ANMAD_glm %>%
#  mutate(num_sites = dplyr::count(site_id)) %>% 
  group_by(sev2, tsf2) %>% 
  mutate(num_occ = sum(pa)) %>% 
  add_tally() %>% 
  mutate(freq = num_occ/n) %>% 
  dplyr::select(sev2, tsf2, freq)


  

ggplot(mod, aes(x=tsf2, y=freq)) +
#  geom_point(aes(colour=sev2)) +
  geom_smooth(aes(colour=sev2), method = "lm") +
  geom_jitter(aes(colour=sev2))




# Now the GLM
bin.glm1 <- glm(pa~sev2, data=ANMAD_glm, family=binomial(link=logit))

plot(bin.glm1)

summary(bin.glm1)
anova(bin.glm1,test="Chisq") # doesn't work with manyglm


g<-glht(bin.glm1, linfct = mcp(sev2 = "Tukey"))
cld(g)

?manyglm

#likelihood ratio test
results.reduced <- glm(data=ANMAD_glm, pa ~ 1, family=binomial)
anova(results.reduced,bin.glm1, test="Chisq")


# Estimated means between groups within each year
means = emmeans(bin.glm1, specs = "sev2", by = "tsf_2cat", adjust = "tukey")

# All pairwise comparisons
paircomp = pairs(means)

# Assigning labels to each groups
cld(means)

#create dataframe to use for labeling richness boxplots
alpha_rich_stats <- as.data.frame(CLD(means))











source("scripts/occ_plot.R")
source("scripts/lmt.R")

sp_dat <- plant_dat_cov_w %>% 
  dplyr::select(site_id, Madia, sev, tsf, sev_tsf)

lmt(sp_dat)

sp_mod1 <- glm(Madia/100 ~ sev, sp_dat, family = gaussian) # use gaussian for cov, binomial for pa?
sp_mod2 <- glm(Madia/100 ~ sev_tsf, sp_dat, family = gaussian)
occ_plot_sev(sp_mod1)
occ_plot_full(sp_mod2)


```

```{r}
# now just for PSME
PSME_glm <- plant_glm %>% filter(species == "PSME")

# Now the GLM
bin.glm1 = glm(pa~sev+tsf_cat,data=PSME_glm,family=binomial)

summary(bin.glm1)
#step(bin.glm1) 

#likelihood ratio test
results.reduced =glm(data=PSME_glm, pa ~ 1, family=binomial)
anova(results.reduced,bin.glm1, test="Chisq")

```

```{r}
# now just for CEIN
CEIN_glm <- plant_glm %>% filter(species == "CEIN")

# Now the GLM
bin.glm1 = glm(pa~sev+tsf_cat,data=CEIN_glm,family=binomial)

summary(bin.glm1)
#step(bin.glm1) 

#likelihood ratio test
results.reduced =glm(data=CEIN_glm, pa ~ 1, family=binomial)
anova(results.reduced,bin.glm1, test="Chisq")


```