---
title: "Introduction"
author: "Chris Adlam"
output: html_document
bibliography: bibliography3.bib
csl: forest-ecology-and-management.csl
---

```{r}
```

# Abstract

Mixed conifer-hardwood forests found along the Oregon and California coasts historically supported a fire regime of frequent, low to moderate severity burning. Since Anglo-American settlement, the near-eradication of Indigenous burning practices and enforcement of fire suppression has nearly erased fire as an ecological force in these mixed evergreen forests. Today, the Karuk Tribe, US Forest Service, and local community organizations have formed the Western Klamath Restoration Partnership (WKRP) to restore this fire regime, which is fundamental to ecological composition, structure and function as well as ecosystem services that fulfill human needs. The WKRP seeks to reduce fuel loads around communities while addressing concerns about the impacts to biodiversity of high severity fire on one hand, and of the exclusion of fire on the other. I investigated how communities of plants, birds, lichens and insects differ between long-unburnt stands, low severity burns and high severity burns. Then I evaluated the response of diversity to two management options used to mitigate the risk of high severity fire by reducing fuels and canopy cover: wildland fire managed for resource benefit (the "passive" option) and forest thinning and prescribed burning (the "active" option). Based on 110 plots across the WKRP project area, low severity burns and unburnt areas did not differ significantly in species composition. In addition, in high severity burns, plant, bird and insect diversity (alpha, beta and gamma) were as high or higher than in low severity/unburnt stands. Lichens were negatively impacted by high severity fire, beginning to recover only after 16 years. Areas burned by multiple wildland fires and thinned/burnt stands had the highest diversity, because they provided habitat for both species preferring high severity burns and those preferring low severity/unburnt stands. My results suggest that management, whether passive (allowing fires to burn and overlap) or active (thinning and burning) can help maintain biodiversity in this fire-dependent landscape.

## Summary

* I recorded all species found in high severity burns (most trees killed, more than 75% of the canopy), low severity burns (a few trees killed, less than 25% of the canopy), and long-unburnt areas (no fires in the last 80 years).

* I found that the number of plant and bird species found in each plot in high severity burns is as high or higher compared with low severity burns and unburnt plots. There was also more difference between the plots in the high severity burns, whereas the low severity and unburnt plots tended to be more similar. Lastly, I found more species in total in the high severity burns than in the low severity and unburnt areas. These results show that forests that haven't had fire in a long time are less diverse; a lot of species use high severity burns but can't live in dense, fire-suppressed forests. A single low severity burn doesn't make a noticeable difference, probably because it doesn't change the canopy cover enough.

* Several kinds of insects also prefer high severity burns, but fire-sensitive lichens aren't found after a high severity burn and only start to grow again after 16 years.

* I also surveyed stands that had burnt several times and thinned and burnt stands that had 30-70% canopy cover left. Diversity in these stands was the highest, significantly higher than either high severity burns or low severity and unburnt stands. These stands are more diverse because both species typical of open areas and high severity burns and those typical of dense, fire-suppressed stands can be found living in them. 

* These results suggest that management solutions proposed by the Karuk Tribe and WKRP, including letting more fires burn in the backcountry (when appropriate), and actively thinning and burning are beneficial to biodiversity as well as reducing fuel levels. Management may need to reduce canopy cover significantly (to 30-60%) where appropriate if conserving and restoring understory species is important.

# Introduction

In Western North American forests adapted to frequent fires predominantly of low to moderate severity, concerns are mounting over the effect of changing fire regimes on biodiversity [@haugoMissingFireQuantifying2019; @hessburgDryForestsWildland2005; @steelFireFrequencyseverityRelationship2015]. The historic fire regime of these forests, described as "mixed severity" [@halofskyMixedseverityFireRegimes2011; @hessburgTammReviewManagement2016; @perryEcologyMixedSeverity2011], has beenaltered by a century of fire suppression and climate change in two contrasting ways: an extreme lack of fire on most of the landscape on one hand, and the increasing extent of high severity fire on the other. The former threatens early seral habitats and open forests [@swansonBiologicalAssociatesEarlyseral2014; @odionExaminingHistoricalCurrent2014; @knappLongtermOverstoryUnderstory2013], while the latter threatens species and ecosystem services associated with mature forests [@millerAlteredFireRegimes2018; @millerPlantCommunityResponses2019]. Despite a broad consensus that the exclusion of fire has been detrimental to biodiversity, disagreement remains over how to balance the ecological need to allow more fire in fire-dependent ecosystems and the need to mitigate the risk of high severity fires to old growth-associated species, communities, and ecosystem services. 

Managers seeking to move away from systematic fire suppression may turn to two approaches to achieve this balance. The active approach is to thin and burn stands to enhance populations of species negatively impacted by fire exclusion and minimize the likelihood of high severity fires in places where there is a concern over the vulnerability of resources and rural communities [@abellaEffectsTreeCutting2015; @kaliesTammReviewAre2016; @waymanInitialResponseMixedconifer2007; @websterLongtermVegetationResponses2010]. However, thinning and burning has been criticized on the grounds that reducing the extent of high severity fire could reduce the availability of ecologically important early seral habitats, while at the same time disturbing mature forest habitats and threatening associated species [@bakerAreHighSeverityFires2015; @odionExaminingHistoricalCurrent2014]. The second approach is to let unplanned fires burn under appropriate weather and fuels conditions; this passive approach would lead to more frequent fires at larger scales, thus reducing fuel loading and canopy homogeneity across more of the landscape [@northUsingFireIncrease2012]. Understanding the impacts of both active and passive forms of management is important to build a consensus over how to meet both fire management and biodiversity targets. 

Such consensus is particularly needed in the context of collaborative landscape management agreements that are becoming increasingly common, particularly on national forests. In the Klamath Mountains of northern California, the Karuk Tribe, United States Forest Service and community and environmental organizations have formed the Western Klamath Restoration Partnership (WKRP) in order to restore the forest and steer the fire regime back towards the pattern of frequent, patchy, low to moderate severity fires that prevailed prior to the disruption of Indigenous fire management and the widespread suppression of lighning-ignited fires [@fryInfluenceHumansClimate2006; @taylorSocioecologicalTransitionsTrigger2016; @crawfordLateHoloceneFire2015]. Extensive planning discussions have taken place to identify zones of agreement among all partners, such as limiting damage to communities from high severity fires and enhancing biodiversity (including both late seral species and fire-dependent, early seral species) [@harlingWesternKlamathRestoration2014; @lakeIntegrationTraditionalWestern2018]. But can management concurrently achieve both of these objectives, or will they necessarily be at odds?

Studies from related forest types such as inland dry forests suggest that treatments that reduce canopy cover can promote biodiversity [@bartuszevigeSynthesisKnowledgeEffects2009], but such results are inconsistent [@willmsEffectsThinningBurning2017] and their applicability to mixed severity forests is questionable [@hessburgTammReviewManagement2016]. In this study, I surveyed biodiversity (birds, plants, lichens and insects) in long-unburnt stands and low severity and high severity single burns. I identified species associated with high severity burns and long unburnt stands as early- and late-seral species respectively. I also surveyed thinned and burnt stands and multiple burns with intermediate canopy cover representative of forest restoration goals aimed at minimizing the risk of high severity burns. To determine whether this type of management is also compatible with biodiversity conservation objectives, I then ask: do areas with intermediate canopies (actively or passively managed) provide habitat for early seral species, late seral species, both, or neither?
