---
title: "Methods"
author: "Chris Adlam"
date: "2/11/2020"
output:
  html_document: default
  pdf_document: default
bibliography: bibliography3.bib
csl: ecology.csl
---

# Methods

## Study area
Located in the Klamath-Siskiyou mountains of northern California, the WKRP is a 1.2 million-acre collaborative landscape restoration effort between the Karuk Tribe, US Forest Service and local NGOs [@harlingWesternKlamathRestoration2014]. The area’s main vegetation class is mixed evergreen forest [@steelFireFrequencyseverityRelationship2015]. The prevalence of hardwoods and Douglas-fir ('Pseudotsuga menziesii') distinguish the Klamath-Siskiyou mixed evergreen forests from those of the Cascade Mountains and Sierra Nevada [@barbourNorthAmericanTerrestrial2000; @whittakerVEGETATIONHISTORYPACIFIC1961]. These forests were historically managed by the Karuk tribe using frequent (~12.5 year interval), low-intensity prescribed burning [@taylorFireHistoryLandscape1998; @taylorSpatialPatternsControls2003a]. One of the main goals of the WKRP is to restore the fire regimes within the Karuk tribe’s aboriginal territory in a way that promotes the resilience of these ecosystems to high severity fire and climate change [@harlingWesternKlamathRestoration2014].

## Data collection
I conducted surveys at 110 sites varying in time-since-fire and burn severity (48 sites surveyed in 2018 and 62 in 2019). Most sites were in mixed evergreen forest, with some in transition areas into dry or moist mixed conifer (classification based on FRID data, @saffordUsingFireReturn2014). The median historic fire return interval in these forest is 13 years [@vandewaterSummaryFireFrequency2011]. Sites sampled were lower elevation (mean 759m, range 241-1500m). They were placed in low severity and high severity burns, defined respectively as <25% canopy mortality and >75% canopy mortality [@millerQuantitativeEvidenceIncreasing2009], in long-unburnt stands (>40 years since last fire), in sites affected by multiple burns, and sites that were thinned and burnt. At all burnt sites, time-since-fire varied from 2 to 32 years. Multiple burns and thinned and burnt sites were placed in areas with intermediate canopy cover (30-65% cover). While it is possible for both to still have high canopy cover (or little canopy), I was only interested in "treatments" (active or passive) that reduce canopy cover significantly. Such canopy reduction corresponds to the level recommended for understory restoration [@abellaEffectsTreeCutting2015] and for mitigating the risk of crown fires [@moghaddasFuelTreatmentEffects2010]. As a result of this approach, the habitats studied follow a gradient of canopy cover (Figure 1). Burn severity was evaluated a priori based on the relative difference normalized burn ratio [@millerQuantifyingBurnSeverity2007] and verified in situ by visually estimating the magnitude of canopy cover reduction. Since the habitats differ mostly by the severity of fire's impact, I will henceforth refer to different "severity categories" for simplicity, even though this is an imperfect description of multiple burn and thinned and burnt sites.

Several tests were used to ensure that the differences observed between site categories were not the product of a climatic or topographic pattern rather than fire history. To test for climate differences, I compared the climatic water deficit (CWD, the difference between potential and actual evapotranspiration). Using the Basin Characterization Model 30-year average for 1981-2010 [@flintFinescaleHydrologicModeling2013], I found no difference between the severity categories (ANOVA, F = 1.41,  p = 0.237). Heat load, which accounts for the effect of slope, aspect and lattitude on insolation and temperature [@mccuneEquationsPotentialAnnual2002], was not different among categories except that it was slightly lower for high severity sites (although this might seem counterintuitive, it is explained by the fact that high severity sites were steeper on average, and heat load decreases with slope gradient on north-facing aspects).  However, due to the limited availability of prescribed burn areas, I had to make some concessions in study design. While there were numerous sites available for the other severity categories, the only prescribed burn sites that met my criteria for minimum size, canopy reduction, and absence of other disturbance factors were located in two project areas. These were higher in elevation on average than the other severity categories (mean = 1101m, 95% CL = 965-1237m) and more clustered (average distance among sites <10km compared to 28-36km for the other severity categories). While these factors limit the generalizability of the patterns observed at these sites, this is a common challenge for studies of prescribed fires. Therefore I still include the prescribed burn sites in the study in the hope that my findings can be used in designing more robust future investigations.

At each site, I recorded aspect, slope and elevation. For all sites, I surveyed plants, epiphytic lichens, and birds. Flying insects were sampled in high and low severity sites and unburnt sites only for logistical reasons. Presence of all plants and lichen species was determined in an 11.3m-radius plot following the Common Stand Exam protocol [@usforestserviceCommonStandExam2008]. Plants were identified using the Jepson manual () and lichens were identified using Mccune (). I conducted two 10-minute bird point counts on separate, non-consecutive days (). Lastly, for high severity, low severity and unburnt sites, I set up a custom-built flight-intercept trap for flying insects that were left out for two days [@russoCompositeInsectTrap2011]. 

## Analysis
I conducted a PERMANOVA analysis to test the significance of dissimilarity between the different severity categories [@mcardleFittingMultivariateModels2001] using the adonis2() function from the vegan package in R [@oksanenVeganPackage2007], with 999 permutations. Then I conducted PERMANOVA pairwise comparisons between each severity category. To minimize the risk of making a type-1 error from carrying out multiple pairwise tests on a single data set, I adjusted the p-values using the Bonferroni correction method [@riceAnalyzingTablesStatistical1989].

Next, I analyzed patterns of alpha, beta and gamma diversity for plants, birds, and lichens. Alpha diversity is equivalent to species richness per plot. I calculated beta diversity, or the amount of variation in species composition and richness between sites within each severity category, using R package vegetarian v1.2 (Charney and Record, 2009). I used the Jaccard index [@jostPartitioningDiversityIndependent2007] to represent the extent to which species are shared in each pair of samples. I compared results between treatments using standard errors from bootstrapping given by the package vegetarian.

To compare the species pool (gamma diversity) between severity categories, I generated sample-based rarefaction curves [@colwellModelsEstimatorsLinking2012] using package iNEXT v. 2.0.20 [@chaoRarefactionExtrapolationHill2014; @hsiehINEXTPackageRarefaction2016]. Estimates were interpolated from site-based incidence data to account for unequal sample sizes [@colwellModelsEstimatorsLinking2012] and then extrapolated to 2× the size of the smallest sample [@chaoRarefactionExtrapolationHill2014]. I compared results between treatments using 95% confidence intervals from bootstrapping.

Insects were not sampled in the multiple burns and thinned and burnt sites, but I include them nevertheless to compare species communities in the unburnt, low severity and high severity burns. Comparisons of alpha, beta and gamma diversity were not as meangingful for insects, because of the small number of taxa (orders or suborders). Instead, I used an indicator species analysis using the function multipatt() in the package indicspecies v1.7.8 [@decaceresAssociationsSpeciesGroups2009] to determine which taxa showed a preference for high severity or low severity and unburnt stands (the latter were pooled because the PERMANOVA suggested their community composition did not differ). 

Lastly, I wanted to determine if the multiple burns and thinned and burnt stands tended to contain species affiliated with high severity burns and/or those associated with low severity and unburnt stands. Four hypotheses were envisioned: 1) Species associated with high severity burns are associated with the actively or passively managed stands; 2) Species associated with unburnt stands and low severity burns are associated with the actively or passively managed stands; 3) Both of these species cohorts are found in the actively or passively managed stands, presumably because they are intermediate in environmental characteristics such as canopy cover; 4) Neither cohort is found in the actively or passively managed stands, presumably because the intermediate canopy cover creates inhospitable conditions for both and favors a completely different species assemblage. To determine which of these four hypothese was correct, I identified species that prefer high severity burns and species that prefer unburnt stands and low severity burns by using a simple criterion: if a species was found twice as frequently in one habitat than the other, I considered that it exhibited a preference for that habitat. Only species that occurred in more than five sites (18% of the total number of sites) were included. For each cohort (those found twice as frequently in the high severity burns and those found twice as frequently in the low severity burns and unburnt stands), I then determined if it was also found twice as frequently in the multiple burns and/or thinned and burnt stands. To determine which of the four hypotheses above was correct, I evaluated the frequency with which species preferring high severity burns or low severity burns and unburnt stands also favored the multiple burns and/or thinned and burnt stands.

were species more likely to be found in high severity burns, low severity burns and unburnt stands, both, or neither

compared the occurrence of species with a strong preference for either HS
or UN/LS habitats in the MULT and Rx habitats, to see if these habitats can be suitable for such species.




